name: Daily Drift Detection

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  drift_detection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "~> 1.5"

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: infra/tf-app

      - name: Terraform Plan (Detect Drift)
        id: plan
        run: |
          terraform plan -detailed-exitcode -out=tf-app.plan || exit_code=$?
          echo "plan_exit_code=${exit_code:-0}" >> "$GITHUB_OUTPUT"
        working-directory: infra/tf-app

      - name: Report Drift Detected
        if: steps.plan.outputs.plan_exit_code == '2'
        run: |
          echo "Drift detected! You may want to investigate."
